/* =============================================================================
 * js/ros/argentina/catalogos_uif.js — catálogos largos del portal SRO de la UIF.
 *
 * GENERADO desde core/paises/argentina/catalogos_uif.json del backend (misma
 * fuente que enums.py): no editar a mano. Textos EXACTOS de las opciones del
 * portal (extraídos el 2026-10-08), erratas incluidas — el robot de carga elige
 * la opción por su texto.
 * ========================================================================== */
(function () {
  "use strict";
  window.CATALOGOS_UIF_AR = {
  paises: [
    "Argentina",
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antártida",
    "Antigua y Barbuda",
    "Antillas Holandesas",
    "Arabia Saudita",
    "Argelia",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Bahrein",
    "Bangladesh",
    "Barbados",
    "Bélgica",
    "Belice",
    "Benín",
    "Bermudas",
    "Bielorrusia",
    "Bolivia",
    "Bosnia-Herzegovina",
    "Botswana",
    "Brasil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Bután",
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Ciudad del Vaticano",
    "Colombia",
    "Comores",
    "Corea del Norte",
    "Corea del Sur",
    "Costa de Marfil",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Dinamarca",
    "Djibouti, Yibuti",
    "Dominica",
    "Dominicana, República",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Emiratos Árabes Unidos",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "España",
    "Estados Unidos",
    "Estonia",
    "Etiopía",
    "Federación Rusa",
    "Filipinas",
    "Finlandia",
    "Fiyi",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Ghana",
    "Gibraltar",
    "Gran Bretaña",
    "Granada",
    "Grecia",
    "Groenlandia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guayana Francesa",
    "Guernsey",
    "Guinea Bissau",
    "Guinea Ecuatorial",
    "Guyana",
    "Haití",
    "Honduras",
    "Hong Kong",
    "Hungría",
    "India",
    "Indonesia",
    "Irán",
    "Iraq",
    "Irlanda",
    "Isla Ascension",
    "Isla Bouvet",
    "Isla De Navidad, Isla Christmas",
    "Isla Jan Mayen y Archipiélago de Svalbard",
    "Isla Man",
    "Isla Pitcairn",
    "Islandia",
    "Islas Caimán",
    "Islas Cocos",
    "Islas Cook",
    "Islas de Heard y McDonald",
    "Islas Feroe",
    "Islas Malvinas",
    "Islas Marshall",
    "Islas Salomón",
    "Islas Turcas y Caicos",
    "Islas Virgenes Americanas",
    "Islas Virgenes Británicas",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jersey",
    "Jordania",
    "Kazajstán",
    "Kenia",
    "Kirguistán",
    "Kiribati",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Letonia",
    "Líbano",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Macao",
    "Macedonia",
    "Madagascar",
    "Malasia",
    "Malawi",
    "Maldivas",
    "Malí",
    "Malta",
    "Marianas del Norte",
    "Marruecos",
    "Martinica",
    "Mauricio",
    "Mauritania",
    "Mayotte",
    "México",
    "Micronesia, Estados Federados de",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Mozambique",
    "Myanmar, Birmania",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Noruega",
    "Nueva Caledonia",
    "Nueva Zelanda",
    "Omán",
    "Países Bajos, Holanda",
    "Pakistán",
    "Palau",
    "Palestina",
    "Panamá",
    "Papúa-Nueva Guinea",
    "Paraguay",
    "Perú",
    "Polinesia Francesa",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reino Unido",
    "República Centroafricana",
    "República Checa",
    "República del Congo",
    "República Democrática del Congo",
    "República Guinea",
    "Reunión",
    "Ruanda",
    "Rumanía",
    "Sáhara Occidental",
    "Samoa",
    "Samoa Americana",
    "San Cristobal y Nevis",
    "San Marino",
    "San Pedro y Miquelón",
    "San Tomé y Príncipe",
    "San Vincente y Granadinas",
    "Santa Elena",
    "Santa Lucía",
    "Santa Sede, Vaticano, Ciudad del Vaticano",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Siria",
    "Somalia",
    "Sri Lanka",
    "Sudáfrica",
    "Sudán",
    "Sudo Georgia y las Islas Sandwich del Sur",
    "Suecia",
    "Suiza",
    "Surinam",
    "Swazilandia",
    "Tadjikistan",
    "Tailandia",
    "Taiwan",
    "Tanzania",
    "Territorio Británico del Océano Indico",
    "Tíbet",
    "Timor Oriental",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad y Tobago",
    "Túnez",
    "Turkmenistan",
    "Turquía",
    "Tuvalu",
    "Ucrania",
    "Uganda",
    "Uruguay",
    "Uzbekistán",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Wallis y Futuna",
    "Yemen",
    "Zaire",
    "Zambia",
    "Zimbabwe",
  ],
  tipos_inusualidad: [
    "La realización de operaciones secuenciales o transferencias electrónicas simultáneas entre distintas jurisdicciones, sin razón aparente.",
    "La realización de operaciones o transacciones de los clientes que por su magnitud, habitualidad o periodicidad excedan las prácticas usuales.",
    "Los montos, tipos, frecuencia y naturaleza de las operaciones que realicen los clientes que no guarden relación con los antecedentes y la actividad económica de ellos.",
    "Los montos inusualmente elevados, la complejidad y las modalidades no habituales de las operaciones que realicen los clientes.",
    "Cuando transacciones de similar naturaleza, cuantía, modalidad o simultaneidad, hagan presumir que se trata de una operación fraccionada a los efectos de evitar la aplicación de los controles de monitoreo y/o alerta.",
    "Cuando los clientes se nieguen a proporcionar información, datos o documentos requeridos por el Sujeto Obligado, con constancia de su pedido, o bien cuando se detecte que la información suministrada por los mismos se encuentre alterada o apócrifa.",
    "Cuando los clientes intenten realizar operaciones con dinero falso.",
    "Situaciones en las cuales los clientes presionen e insistan en que una determinada operación se realice con extrema rapidez, evitando los trámites predefinidos y sin justificar el motivo de su apremio.",
    "Situaciones en las cuales se detecte que una persona suplantare, se apoderare o intentare suplantar la identidad de una persona humana sin su consentimiento, utilizando los datos de identificación de ésta.",
    "Toma de conocimiento que indique que un cliente está siendo investigado o procesado por delitos de lavado de activos y financiamiento del terrorismo, u otros relacionados.",
    "Situaciones en las que una persona humana figura como firma autorizada para el manejo de numerosas cuentas a la vez, pertenecientes a diferentes personas o empresas, sin que exista justificación aparente.",
    "Triangulación de fondos entre cuentas del cliente, sus familiares, sociedades y terceros relacionados sin justificación económica aparente.",
    "Operaciones de volumen elevado situadas en la Zona de Seguridad de Fronteras establecidas por el Decreto N° 253/18, que no guarden relación con las prácticas usuales.",
    "Cuando existiera el mismo domicilio en cabeza de distintas personas o estructuras jurídicas, y no existiere razón económica o legal para ello.",
    "Cuando existieran operaciones de distintas cuentas asociadas o vinculadas con un mismo dispositivo electrónico o cuando existiera una cuenta asociada a varios dispositivos electrónicos, sin justificación aparente.",
    "Cuando existieran operaciones inconsistentes con las prácticas habituales, teniendo en especial consideración si su actividad principal está vinculada con la operatoria “off shore” y/o con países determinados como de baja o nula tributación por las autoridades competentes.",
    "Cuando se tome conocimiento que el cliente opera con fondos de terceros.",
    "Cuando existan discrepancias entre la información aportada por el cliente y la información detectada por los sistemas de monitoreo.",
    "Cuando una cuenta reciba fondos de terceros e inmediatamente estos fondos sean transferidos a otras cuentas o sacados en efectivo desde cajeros automáticos.",
    "Alta concentración, sin causa aparente, de compras de un cliente en un mismo establecimiento adherido, por montos significativos.",
    "Saldo acreedor significativo en la cuenta del establecimiento adherido que no guarda relación con los antecedentes de su situación patrimonial.",
    "Adquisición de una suma elevada de cheques de viajero y presentación al cobro por parte del comprador en un período de tiempo irrazonablemente corto o, por parte de un único beneficiario sin motivo que lo explique.",
    "Presentación al cobro del cheque del viajero por parte de una persona física o jurídica cuya actividad no justifique la posesión del mismo.",
    "Las situaciones de las que, mediante la combinación parcial de algunas pautas establecidas en los incisos precedentes u otros indicios, pudiera presumirse la configuración de conductas que excedan los parámetros normales y habituales de la actividad considerada.",
    "Clientes no residentes en el país, con excepción de aquellos que tengan el carácter de turistas y realicen operaciones de compra y venta de divisa extranjera para tales fines.",
    "Personas o estructuras jurídicas que sean vehículos de tenencia de activos personales.",
    "Actividades comerciales con uso intensivo de dinero en efectivo cuando ello no resulte ajustado a la actividad que desarrolla el cliente.",
    "Respecto de las relaciones comerciales con personas humanas, jurídicas u otras estructuras jurídicas, e instituciones financieras procedentes de países, jurisdicciones, o territorios respecto de los cuales la República Argentina haya expresado su preocupación por las debilidades de sus sistemas LA/FT/FP y dispuesto medidas específicas de mitigación de riesgos en función de un mayor riesgo.",
    "Respecto de las relaciones comerciales con personas humanas, jurídicas u otras estructuras jurídicas, e instituciones financieras procedentes de países identificados, por fuentes verosímiles, como proveedores de financiamiento o apoyo a actividades terroristas, o que tienen a organizaciones terroristas designadas operando dentro de su país.",
    "Respecto de las relaciones comerciales con personas humanas, jurídicas u otras estructuras jurídicas, e instituciones financieras procedentes de países, jurisdicciones, o territorios sujetos a sanciones, embargos o medidas de naturaleza similar aplicada por organismos internacionales como, por ejemplo, la Organización de Naciones Unidas.",
    "Respecto de las relaciones comerciales y operaciones relacionadas con personas humanas, jurídicas u otras estructuras, e instituciones financieras procedentes de países, de jurisdicciones bajo monitoreo intensificado conforme lo establecido por el GAFI.",
    "Otras operaciones no mencionadas en los ítems precedentes",
  ],
  actividades: [
    "10001 Empleado",
    "10002 Jubilado/Pensionado",
    "10003 Sin Actividad Declarada",
    "11111 Cultivo de arroz",
    "11112 Cultivo de trigo",
    "11119 Cultivo de cereales excepto los forrajeros y las semillas n.c.p.(Incluye alforfón, cebada cervecera,etc.)",
    "11121 Cultivo de maíz",
    "11122 Cultivo de sorgo granífero",
    "11129 Cultivo de cereales forrajeros n.c.p.(Incluye alpiste, avena, cebada forrajera, centeno, mijo, etc.)",
    "11131 Cultivo de soja",
    "11132 Cultivo de girasol",
    "11139 Cultivo de oleaginosas n.c.p.(Incluye los cultivos de oleaginosas para aceites comestibles y/o uso industrial: cártamo, colza, jojoba, lino oleaginoso, maní, olivo para aceite, ricino, sésamo, tung, etc.)",
    "11140 Cultivo de pastos forrajeros(Incluye alfalfa, moha, pastos consociados, sorgo azucarado y forrajero,etc.)",
    "11210 Cultivo de papa, batata y mandioca",
    "11221 Cultivo de tomate",
    "11229 Cultivo de bulbos, brotes, raíces y hortalizas de frutos n.c.p.(Incluye ají, ajo, alcaparra, berenjena,cebolla, calabaza, espárrago, frutilla, melón, pepino, pimiento, sandía, zanahoria, zapallo, zapallito, etc.)",
    "11230 Cultivo de hortalizas de hoja y de otras hortalizas frescas(Incluye acelga, apio, cebolla de verdeo,choclo, coles, espinaca, lechuga, perejil, radicheta, repollo, etc.)",
    "11241 Cultivo de legumbres frescas(Incluye arveja, chaucha, haba, lupino, poroto, etc.)",
    "11242 Cultivo de legumbres secas(Incluye arveja, garbanzo, haba, lenteja, poroto, etc.)",
    "11251 Cultivo de flores",
    "11252 Cultivo de plantas ornamentales",
    "11311 Cultivo de manzana y pera",
    "11319 Cultivo de frutas de pepita n.c.p.(Incluye membrillo, níspero, etc.)",
    "11320 Cultivo de frutas de carozo(Incluye cereza, ciruela, damasco, durazno, pelón, etc.)",
    "11330 Cultivo de frutas cítricas(Incluye bergamota, lima, limón, mandarina, naranja, pomelo,kinoto, etc.)",
    "11340 Cultivo de nueces y frutas secas(Incluye almendra, avellana, castaña, nuez, pistacho,etc.)",
    "11390 Cultivo de frutas n.c.p.(Incluye ananá, banana, higo, kiwi, mamón, palta, uva de mesa,etc.)",
    "11411 Cultivo de algodón",
    "11419 Cultivo de plantas para la obtención de fibras n.c.p.(Incluye abacá, cáñamo, formio, lino textil, maíz de Guinea, ramio, yute, etc.)",
    "11421 Cultivo de caña de azúcar",
    "11429 Cultivo de plantas sacaríferas n.c.p.(Incluye remolacha azucarera, etc.)",
    "11430 Cultivo de vid para vinificar",
    "11440 Cultivo de té, yerba mate y otras plantas cuyas hojas se utilizan para preparar bebidas(infusiones)",
    "11450 Cultivo de tabaco",
    "11460 Cultivo de especias (de hoja, de semilla, de flor y de fruto) y de plantas aromáticas ymedicinales",
    "11490 Cultivos industriales n.c.p.(Incluye olivo para conserva, palmitos, etc.)",
    "11511 Producción de semillas híbridas de cereales y oleaginosas",
    "11512 Producción de semillas varietales o autofecundadas de cereales, oleaginosas, y forrajeras",
    "11513 Producción de semillas de hortalizas y legumbres, flores y plantas ornamentales y árboles frutales",
    "11519 Producción de semillas de cultivos agrícolas n.c.p.",
    "11520 Producción de otras formas de propagación de cultivos agrícolas(Incluye gajos, bulbos,estacas enraizadas o no, esquejes, plantines, etc.)",
    "12111 Cría de ganado bovino -excepto en cabañas y para la producción de leche-",
    "12112 Invernada de ganado bovino excepto el engorde en corrales (Fed-Lot)",
    "12113 Engorde en corrales (Fed-Lot)",
    "12120 Cría de ganado ovino, excepto en cabañas y para la producción de lana",
    "12130 Cría de ganado porcino, excepto en cabañas",
    "12140 Cría de ganado equino, excepto en haras(Incluye equinos de trabajo)",
    "12150 Cría de ganado caprino, excepto en cabañas y para producción de leche",
    "12161 Cría de ganado bovino en cabañas(Incluye la producción de semen)",
    "12162 Cría de ganado ovino, porcino y caprino en cabañas(Incluye la producción de semen)",
    "12163 Cría de ganado equino en haras(Incluye la producción de semen)",
    "12169 Cría en cabañas de ganado n.c.p.",
    "12171 Producción de leche de ganado bovino",
    "12179 Producción de leche de ganado n.c.p.(Incluye la cría de ganado de búfala, cabra, etc.para la producciónde leche)",
    "12181 Producción de lana",
    "12182 Producción de pelos(Incluye la cría de caprinos, camélidos, etc., para la obtención depelos)",
    "12190 Cría de ganado n.c.p.(Incluye la cría de alpaca, asno, búfalo, guanaco, llama, mula, vicuña, etc.)",
    "12211 Cría de aves para producción de carne",
    "12212 Cría de aves para producción de huevos(Incluye pollitos BB para postura)",
    "12220 Producción de huevos",
    "12230 Apicultura(Incluye la producción de miel, jalea real, polen, propóleo, etc.)",
    "12241 Cría de animales para la obtención de pieles y cueros",
    "12242 Cría de animales para la obtención de pelos",
    "12243 Cría de animales para la obtención de plumas",
    "12290 Cría de animales y obtención de productos de origen animal, n.c.p.(Incluye ciervo, conejo -excepto parapelos-, gato, gusano de seda, lombriz, pájaro, perro, rana, animales para experimentación, caracoles vivos, frescos, congelados y secos -excepto marinos",
    "14111 Servicios de labranza, siembra, transplante y cuidados culturales",
    "14112 Servicios de pulverización, desinfección y fumigación aérea y terrestre, excepto la manual",
    "14119 Servicios de maquinaria agrícola n.c.p., excepto los de cosecha mecánica(Incluye enfardado, enrollado, envasado - silo-pack -, clasificación y secado, etc.)",
    "14120 Servicios de cosecha mecánica(Incluye la cosecha mecánica de granos, caña de azúcar, algodón, forrajes,el enfardado, enrrollado, etc.)",
    "14130 Servicios de contratistas de mano de obra agrícola(Incluye la poda de árboles, transplante, fumigación ydesinfección manual, cosecha manual de citrus, algodón, etc.)",
    "14190 Servicios agrícolas n.c.p(Incluye planificación y diseño Paisajista, plantación y mantenimiento de jardines, parques y cementerios, riego, polinización o alquiler de colmenas, control acústico de plagas, etc.)",
    "14210 Inseminación artificial y servicios n.c.p. para mejorar la reproducción de los animalesy el rendimientode sus productos",
    "14220 Servicios de contratistas de mano de obra pecuaria(Incluye arreo, castración de aves,esquila de ovejas,recolección de estiércol, etc. )",
    "14291 Servicios para el control de plagas, baños parasiticidas, etc.",
    "14292 Albergue y cuidado de animales de terceros",
    "14299 Servicios pecuarios n.c.p., excepto los veterinarios",
    "15010 Caza y captura de animales vivos y repoblación de animales de caza(Incluye la caza de animales paraobtener carne, pieles y cueros y la captura de animales vivos para zoológicos, animales de compañía, para investigación, etc.)",
    "15020 Servicios para la caza",
    "20110 Plantación de bosques",
    "20120 Repoblación y conservación de bosques nativos y zonas forestadas",
    "20130 Explotación de viveros forestales(Incluye propagación de especies forestales)",
    "20210 Extracción de productos forestales de bosques cultivados(Incluye tala de árboles, desbaste de troncosyproducción de madera en bruto, rollizos, leña, postes, carbón, carbonilla y productos forestales n.c.p.)",
    "20220 Extracción de productos forestales de bosques nativos(Incluye tala de árboles, desbaste de troncos yproducción de madera en bruto, leña, postes, carbón, carbonilla, la extracción de rodrigones, varas, varillas y la recolección de crines vegetales, gomas n",
    "20310 Servicios forestales de extracción de madera(Incluye tala de árboles, acarreo y transporte en el interior del bosque, servicios realizados de terceros, etc.)",
    "20390 Servicios forestales excepto los relacionados con la extracción de madera(Incluye protección contra incendios, evaluación de masas forestales en pie, estimación del valor de la madera, etc.)",
    "50110 Pesca marítima, costera y de altura(Incluye peces, crustáceos, moluscos y otros animales acuáticos)",
    "50120 Pesca continental, fluvial y lacustre",
    "50130 Recolección de productos marinos(Incluye la recolección de algas marinas y otras plantas acuáticas, corales, esponjas)",
    "50200 Explotación de criaderos de peces, granjas piscícolas y otros frutos acuáticos (acuicultura)",
    "50300 Servicios para la pesca",
    "101000 Extracción y aglomeración de carbón(Incluye la producción de hulla no aglomerada, antracita, carbón bituminoso no aglomerado, briquetas, ovoides y combustibles sólidos análogos a base de hulla, etc.)",
    "102000 Extracción y aglomeración de lignito(Incluye la producción de lignito aglomerado y noaglomerado)",
    "103000 Extracción y aglomeración de turba(Incluye la producción de turba utilizada como corrector de suelos)",
    "111000 Extracción de petróleo crudo y gas natural(Incluye gas natural licuado y gaseoso, arenas alquitraníferas, esquistos bituminosos o lutitas, aceites de petróleo y de minerales bituminosos, petróleo, coque de petróleo, etc.)",
    "112000 Actividades de servicios relacionadas con la extracción de petróleo y gas, excepto lasactividades deprospección",
    "120000 Extracción de minerales y concentrados de uranio y torio",
    "131000 Extracción de minerales de hierro(Incluye hematitas, limonitas, magnetitas, siderita,etc.)",
    "132000 Extracción de minerales metalíferos no ferrosos, excepto minerales de uranio y torio(Incluye aluminio, cobre, estaño, manganeso, níquel, oro, plata, plomo, volframio, antimonio, bismuto, cinc, molibdeno, titanio, circonio, niobio, tántalo, vanadio, cromo,",
    "141100 Extracción de rocas ornamentales(Incluye areniscas, cuarcita, dolomita, granito, mármol, piedra laja,pizarra, pórfido, serpentina , etc.)",
    "141200 Extracción de piedra caliza y yeso(Incluye caliza, castina, conchilla, riolita, yeso natural, anhidrita,etc.)",
    "141300 Extracción de arenas, canto rodado y triturados pétreos(Incluye arena para construcción, arena silícea,otras arenas naturales, canto rodado, dolomita triturada, granito triturado, piedra partida y otros triturados pétreos, etc.)",
    "141400 Extracción de arcilla y caolín(Incluye andalucita, arcillas, bentonita, caolín, pirofilita, silimanita,mullita, tierra de chamota o de dinas, etc.)",
    "142110 Extracción de minerales para la fabricación de abonos excepto turba.(Incluye guano, silvita, silvinita yotras sales de potasio naturales, etc.)",
    "142120 Extracción de minerales para la fabricación de productos químicos(Incluye azufre, boracita e hidroboracita, calcita, celestina, colemanita, fluorita, litio y sales de litio naturales, sulfato de aluminio, sulfato de hierro, sulfato de magnesio, sulfato de",
    "142200 Extracción de sal en salinas y de roca",
    "142900 Explotación de minas y canteras n.c.p.(Incluye amianto, baritina, cuarzo, diatomita, piedra pómez, ágata, agua marina, amatista, cristal de roca, rodocrosita, topacio, corindón, feldespato, mica, zeolita, perlita, granulado volcánico, puzolana, toba, talc",
    "151111 Matanza de ganado bovino",
    "151112 Procesamiento de carne de ganado bovino(Incluye los mataderos y frigoríficos que sacrifican principalmente ganado bovino)",
    "151113 Saladero y peladero de cueros de ganado bovino",
    "151120 Matanza y procesamiento de carne de aves",
    "151130 Elaboración de fiambres y embutidos",
    "151140 Matanza de ganado excepto el bovino y procesamiento de su carne(Incluye ganado ovino,porcino, equino, búfalo, etc.)",
    "151191 Fabricación de aceites y grasas de origen animal",
    "151199 Matanza de animales n.c.p. y procesamiento de su carne; elaboración de subproductos cárnicos n.c.p.",
    "151201 Elaboración de pescados de mar, crustáceos y productos marinos n.c.p.",
    "151202 Elaboración de pescados de ríos y lagunas y otros productos fluviales y lacustres",
    "151203 Fabricación de aceites, grasas, harinas y productos a base de pescados n.c.p.",
    "151310 Preparación de conservas de frutas, hortalizas y legumbres",
    "151320 Elaboración de jugos naturales y sus concentrados, de frutas, hortalizas y legumbres",
    "151330 Elaboración y envasado de dulces, mermeladas y jaleas",
    "151340 Elaboración de frutas, hortalizas y legumbres congeladas",
    "151390 Elaboración de frutas, hortalizas y legumbres deshidratadas o desecadas; preparación n.c.p. de frutas,hortalizas y legumbres(Incluye la elaboración de harina y escamas de papa, sémola de hortalizas y legumbres, frutas, hortalizas y legumbres deshidratadas",
    "151410 Elaboración de aceites y grasas vegetales sin refinar y sus subproductos; elaboraciónde aceite virgen",
    "151420 Elaboración de aceites y grasas vegetales refinadas(No incluye aceite de maíz)",
    "151430 Elaboración de margarinas y grasas vegetales comestibles similares",
    "152010 Elaboración de leches y productos lácteos deshidratados(Incluye la estandarización, homogeneización,pasteurización y esterilización de leche, la elaboración de leches chocolatadas y otras leches saborizadas, leches condensadas, leche en polvo, dulce de le",
    "152020 Elaboración de quesos(Incluye la producción de suero)",
    "152030 Elaboración industrial de helados(No incluye las heladerías artesanales)",
    "152090 Elaboración de productos lácteos n.c.p.(Incluye la producción de caseínas, caseinatoslácteos, cremas, manteca, postres, etc.)",
    "153110 Molienda de trigo",
    "153120 Preparación de arroz",
    "153131 Elaboración de alimentos a base de cereales",
    "153139 Preparación y molienda de legumbres y cereales n.c.p. (excepto trigo)",
    "153200 Elaboración de almidones y productos derivados del almidón(Incluye la elaboración de glucosa, gluten,aceites de maíz)",
    "153300 Elaboración de alimentos preparados para animales",
    "154110 Elaboración de galletitas y bizcochos",
    "154120 Elaboración industrial de productos de panadería, excluido galletitas y bizcochos(Incluye la elaboraciónen establecimientos con más de 10 ocupados)",
    "154191 Elaboración de masas y productos de pastelería",
    "154199 Elaboración de productos de panadería n.c.p.(Incluye la elaboración de churros, prepizzas, masas fritas,de hojaldre, etc.en establecimientos de hasta 10 ocupados)",
    "154200 Elaboración de azúcar",
    "154301 Elaboración de cacao, chocolate y productos a base de cacao",
    "154309 Elaboración de productos de confitería n.c.p.(Incluye caramelos, frutas confitadas, pastillas, gomasdemascar, etc.)",
    "154410 Elaboración de pastas alimentarias frescas",
    "154420 Elaboración de pastas alimentarias secas",
    "154911 Tostado, torrado y molienda de café",
    "154912 Elaboración y molienda de hierbas aromáticas y especias",
    "154920 Preparación de hojas de té",
    "154930 Elaboración de yerba mate",
    "154991 Elaboración de extractos, jarabes y concentrados",
    "154992 Elaboración de vinagres",
    "154999 Elaboración de productos alimenticios n.c.p.(Incluye la elaboración de polvos para preparar postres ygelatinas, levadura, productos para copetín, sopas y concentrados, sal de mesa, mayonesa, mostaza, etc.)",
    "155110 Destilación de alcohol etílico",
    "155120 Destilación, rectificación y mezcla de bebidas espiritosas",
    "155210 Elaboración de vinos(Incluye el fraccionamiento)",
    "155290 Elaboración de sidra y otras bebidas alcohólicas fermentadas a partir de frutas",
    "155300 Elaboración de cerveza, bebidas malteadas y de malta",
    "155411 Embotellado de aguas naturales y minerales",
    "155412 Fabricación de sodas",
    "155420 Elaboración de bebidas gaseosas, excepto soda",
    "155490 Elaboración de hielo, jugos envasados para diluir y otras bebidas no alcohólicas(Incluye los jugos paradiluir o en polvo llamados sintéticos o de un contenido en jugos naturales inferior al 50%)",
    "160010 Preparación de hojas de tabaco",
    "160091 Elaboración de cigarrillos",
    "160099 Elaboración de productos de tabaco n.c.p.",
    "171111 Desmotado de algodón; preparación de fibras de algodón",
    "171112 Preparación de fibras textiles vegetales excepto de algodón(Incluye la preparación defibras de yute,ramio, cáñamo y lino)",
    "171120 Preparación de fibras animales de uso textil, incluso lavado de lana",
    "171131 Fabricación de hilados de lana y sus mezclas",
    "171132 Fabricación de hilados de algodón y sus mezclas",
    "171139 Fabricación de hilados textiles excepto de lana y de algodón",
    "171141 Fabricación de tejidos (telas) planos de lana y sus mezclas",
    "171142 Fabricación de tejidos (telas) planos de algodón y sus mezclas",
    "171143 Fabricación de tejidos (telas) planos de fibras manufacturadas y seda",
    "171148 Fabricación de tejidos (telas) planos de fibras textiles n.c.p.(Incluye hilanderías ytejedurías integradas)",
    "171149 Fabricación de productos de tejeduría n.c.p.",
    "171200 Acabado de productos textiles",
    "172101 Fabricación de frazadas, mantas, ponchos, colchas, cobertores, etc.",
    "172102 Fabricación de ropa de cama y mantelería",
    "172103 Fabricación de artículos de lona y sucedáneos de lona",
    "172104 Fabricación de bolsas de materiales textiles para productos a granel",
    "172109 Fabricación de artículos confeccionados de materiales textiles excepto prendas de vestir n.c.p.",
    "172200 Fabricación de tapices y alfombras",
    "172300 Fabricación de cuerdas, cordeles, bramantes y redes",
    "172900 Fabricación de productos textiles n.c.p.",
    "173010 Fabricación de medias",
    "173020 Fabricación de suéteres y artículos similares de punto",
    "173090 Fabricación de tejidos y artículos de punto n.c.p.",
    "181110 Confección de ropa interior, prendas para dormir y para la playa",
    "181120 Confección de indumentaria de trabajo, uniformes, guardapolvos y sus accesorios",
    "181130 Confección de indumentaria para bebés y niños",
    "181191 Confección de pilotos e impermeables",
    "181192 Fabricación de accesorios de vestir excepto de cuero",
    "181199 Confección de prendas de vestir n.c.p., excepto las de piel, cuero y sucedáneos, pilotos e impermeables",
    "181201 Fabricación de accesorios de vestir de cuero",
    "181202 Confección de prendas de vestir de cuero",
    "182001 Confección de prendas de vestir de piel y sucedáneos",
    "182009 Terminación y teñido de pieles; fabricación de artículos de piel n.c.p.",
    "191100 Curtido y terminación de cueros",
    "191200 Fabricación de maletas, bolsos de mano y similares, artículos de talabartería y artículos de cuero n.c.p.",
    "192010 Fabricación de calzado de cuero, excepto el ortopédico",
    "192020 Fabricación de calzado de tela, plástico, goma, caucho y otros materiales, excepto calzado ortopédicoy de asbesto",
    "192030 Fabricación de partes de calzado",
    "201000 Aserrado y cepillado de madera",
    "202100 Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados;tableros laminados; tableros de partículas y tableros y paneles n.c.p.(Incluye la fabricación de madera terciada y machimbre)",
    "202201 Fabricación de aberturas y estructuras de madera para la construcción",
    "202202 Fabricación de viviendas prefabricadas de madera",
    "202300 Fabricación de recipientes de madera",
    "202901 Fabricación de artículos de cestería, caña y mimbre",
    "202902 Fabricación de ataúdes",
    "202903 Fabricación de artículos de madera en tornerías",
    "202904 Fabricación de productos de corcho",
    "202909 Fabricación de productos de madera n.c.p",
    "210101 Fabricación de pulpa de madera",
    "210102 Fabricación de papel y cartón excepto envases",
    "210201 Fabricación de envases de papel",
    "210202 Fabricación de envases de cartón",
    "210910 Fabricación de artículos de papel y cartón de uso doméstico e higiénico sanitario",
    "210990 Fabricación de artículos de papel y cartón n.c.p.",
    "221100 Edición de libros, folletos, partituras y otras publicaciones",
    "221200 Edición de periódicos, revistas y publicaciones periódicas",
    "221300 Edición de grabaciones",
    "221900 Edición n.c.p.",
    "222101 Impresión de diarios y revistas",
    "222109 Impresión excepto de diarios y revistas",
    "222200 Servicios relacionados con la impresión",
    "223000 Reproducción de grabaciones",
    "231000 Fabricación de productos de hornos de coque",
    "232000 Fabricación de productos de la refinación del petróleo",
    "233000 Fabricación de combustible nuclear",
    "241110 Fabricación de gases comprimidos y licuados.",
    "241120 Fabricación de curtientes naturales y sintéticos.",
    "241130 Fabricación de materias colorantes básicas, excepto pigmentos preparados.",
    "241180 Fabricación de materias químicas inorgánicas básicas n.c.p.",
    "241190 Fabricación de materias químicas orgánicas básicas n.c.p.(Incluye la fabricación de alcoholes exceptoeletílico, sustancias químicas para la elaboración de sustancias plásticas, etc.)",
    "241200 Fabricación de abonos y compuestos de nitrógeno",
    "241301 Fabricación de resinas y cauchos sintéticos",
    "241309 Fabricación de materias plásticas en formas primarias n.c.p.",
    "242100 Fabricación de plaguicidas y productos químicos de uso agropecuario",
    "242200 Fabricación de pinturas; barnices y productos de revestimiento similares; tintas de imprenta y masillas",
    "242310 Fabricación de medicamentos de uso humano y productos farmacéuticos",
    "242320 Fabricación de medicamentos de uso veterinario",
    "242390 Fabricación de productos de laboratorio, sustancias químicas medicinales y productos botánicos n.c.p.",
    "242411 Fabricación de preparados para limpieza, pulido y saneamiento",
    "242412 Fabricación de jabones y detergentes",
    "242490 Fabricación de cosméticos, perfumes y productos de higiene y tocador",
    "242901 Fabricación de tintas",
    "242902 Fabricación de explosivos, municiones y productos de pirotecnia",
    "242903 Fabricación de colas, adhesivos, aprestos y cementos excepto los odontológicos obtenidos de sustanciasminerales y vegetales",
    "242909 Fabricación de productos químicos n.c.p.(Incluye la producción de aceites esenciales,etc.)",
    "243000 Fabricación de fibras manufacturadas",
    "251110 Fabricación de cubiertas y cámaras",
    "251120 Recauchutado y renovación de cubiertas",
    "251901 Fabricación de autopartes de caucho excepto cámaras y cubiertas",
    "251909 Fabricación de productos de caucho n.c.p.",
    "252010 Fabricación de envases plásticos",
    "252090 Fabricación de productos plásticos en formas básicas y artículos de plástico n.c.p., excepto muebles",
    "261010 Fabricación de envases de vidrio",
    "261020 Fabricación y elaboración de vidrio plano",
    "261091 Fabricación de espejos y vitrales",
    "261099 Fabricación de productos de vidrio n.c.p.",
    "269110 Fabricación de artículos sanitarios de cerámica",
    "269191 Fabricación de objetos cerámicos para uso industrial y de laboratorio",
    "269192 Fabricación de objetos cerámicos para uso doméstico excepto artefactos sanitarios",
    "269193 Fabricación de objetos cerámicos excepto revestimientos de pisos y paredes n.c.p.",
    "269200 Fabricación de productos de cerámica refractaria",
    "269301 Fabricación de ladrillos",
    "269302 Fabricación de revestimientos cerámicos",
    "269309 Fabricación de productos de arcilla y cerámica no refractaria para uso estructural n.c.p.",
    "269410 Elaboración de cemento",
    "269421 Elaboración de yeso",
    "269422 Elaboración de cal",
    "269510 Fabricación de mosaicos",
    "269591 Fabricación de artículos de cemento y fibrocemento",
    "269592 Fabricación de premoldeadas para la construcción",
    "269600 Corte, tallado y acabado de la piedra(Incluye mármoles y granitos, etc.)",
    "269910 Elaboración primaria n.c.p. de minerales no metálicos",
    "269990 Fabricación de productos minerales no metálicos n.c.p.",
    "271001 Fundición en altos hornos y acerías. Producción de lingotes, planchas o barras",
    "271002 Laminación y estirado",
    "271009 Fabricación en industrias básicas de productos de hierro y acero n.c.p.",
    "272010 Elaboración de aluminio primario y semielaborados de aluminio",
    "272090 Producción de metales no ferrosos n.c.p. y sus semielaborados",
    "273100 Fundición de hierro y acero",
    "273200 Fundición de metales no ferrosos",
    "281101 Fabricación de carpintería metálica",
    "281102 Fabricación de estructuras metálicas para la construcción",
    "281200 Fabricación de tanques, depósitos y recipientes de metal",
    "281300 Fabricación de generadores de vapor",
    "289100 Forjado, prensado, estampado y laminado de metales; pulvimetalurgia",
    "289200 Tratamiento y revestimiento de metales; obras de ingeniería mecánica en general realizadas a cambio deuna retribución o por contrata",
    "289301 Fabricación de herramientas manuales y sus accesorios",
    "289302 Fabricación de artículos de cuchillería y utensillos de mesa y de cocina",
    "289309 Fabricación de cerraduras, herrajes y artículos de ferretería n.c.p.(No incluye clavos, productos debulonería, vajilla de mesa y de cocina, etc.)",
    "289910 Fabricación de envases metálicos",
    "289991 Fabricación de tejidos de alambre",
    "289992 Fabricación de cajas de seguridad",
    "289993 Fabricación de productos metálicos de tornería y/o matricería",
    "289999 Fabricación de productos metálicos n.c.p.(Incluye clavos, productos de bulonería, vajilla de mesa y de cocina, etc.)",
    "291100 Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas",
    "291200 Fabricación de bombas; compresores; grifos y válvulas",
    "291300 Fabricación de cojinetes; engranajes; trenes de engranaje y piezas de transmisión",
    "291400 Fabricación de hornos; hogares y quemadores",
    "291500 Fabricación de equipo de elevación y manipulación(Incluye la fabricación de ascensores, escaleras mecánicas, montacargas, etc.)",
    "291900 Fabricación de maquinaria de uso general n.c.p.",
    "292110 Fabricación de tractores",
    "292190 Fabricación de maquinaria agropecuaria y forestal, excepto tractores",
    "292200 Fabricación de máquinas herramienta",
    "292300 Fabricación de maquinaria metalúrgica",
    "292400 Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción(Incluye la fabricación de máquinas y equipos viales)",
    "292500 Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco",
    "292600 Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestiry cueros",
    "292700 Fabricación de armas y municiones",
    "292901 Fabricación de maquinaria para la industria del papel y las artes gráficas",
    "292909 Fabricación de maquinaria de uso especial n.c.p.",
    "293010 Fabricación de cocinas, calefones, estufas y calefactores de uso doméstico no eléctricos",
    "293020 Fabricación de heladeras, freezers, lavarropas y secarropas",
    "293091 Fabricación de máquinas de coser y tejer",
    "293092 Fabricación de ventiladores, extractores y acondicionadores de aire, aspiradoras y similares",
    "293093 Fabricación de enceradoras, pulidoras, batidoras, licuadoras y similares",
    "293094 Fabricación de planchas, calefactores, hornos eléctricos, tostadoras y otros aparatos generadores de calor",
    "293095 Fabricación de artefactos para iluminación excepto los eléctricos",
    "293099 Fabricación de aparatos y accesorios eléctricos n.c.p.",
    "300000 Fabricación de maquinaria de oficina, contabilidad e informática",
    "311000 Fabricación de motores, generadores y transformadores eléctricos",
    "312000 Fabricación de aparatos de distribución y control de la energía eléctrica",
    "313000 Fabricación de hilos y cables aislados",
    "314000 Fabricación de acumuladores y de pilas y baterías primarias",
    "315000 Fabricación de lámparas eléctricas y equipo de iluminación(Incluye la fabricación de letreros luminosos)",
    "319000 Fabricación de equipo eléctrico n.c.p.",
    "321000 Fabricación de tubos, válvulas y otros componentes electrónicos",
    "322000 Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilos",
    "323000 Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y video,y productos conexos",
    "331100 Fabricación de equipo médico y quirúrgico y de aparatos ortopédicos",
    "331200 Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otrosfines, exceptoelequipo de control de procesos industriales",
    "331300 Fabricación de equipo de control de procesos industriales",
    "332001 Fabricación de aparatos y accesorios para fotografía excepto películas, placas y papeles sensibles",
    "332002 Fabricación de lentes y otros artículos oftálmicos",
    "332003 Fabricación de instrumentos de óptica",
    "333000 Fabricación de relojes",
    "341000 Fabricación de vehículos automotores(Incluye la fabricación de motores para automotores)",
    "342000 Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques",
    "343000 Fabricación de partes; piezas y accesorios para vehículos automotores y sus motores",
    "351100 Construcción y reparación de buques(Incluye construcción de motores y piezas para navíos, etc.)",
    "351200 Construcción y reparación de embarcaciones de recreo y deporte",
    "352000 Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías",
    "353000 Fabricación y reparación de aeronaves",
    "359100 Fabricación de motocicletas",
    "359200 Fabricación de bicicletas y de sillones de ruedas para inválidos",
    "359900 Fabricación de equipo de transporte n.c.p.",
    "361010 Fabricación de muebles y partes de muebles, principalmente de madera",
    "361020 Fabricación de muebles y partes de muebles, principalmente de otros materiales (metal,plástico, etc.)",
    "361030 Fabricación de somieres y colchones",
    "369101 Fabricación de joyas y artículos conexos",
    "369102 Fabricación de objetos de platería y artículos enchapados",
    "369200 Fabricación de instrumentos de música",
    "369300 Fabricación de artículos de deporte(Incluye equipos de deporte, para gimnasios y campos de juegos, equipos de pesca y camping, etc., excepto indumentaria deportiva)",
    "369400 Fabricación de juegos y juguetes",
    "369910 Fabricación de lápices, lapiceras, bolígrafos, sellos y artículos similares para oficinas y artistas",
    "369920 Fabricación de cepillos y pinceles",
    "369991 Fabricación de fósforos",
    "369992 Fabricación de paraguas",
    "369999 Industrias manufactureras n.c.p.(Incluye fabricación de cochecitos de bebé, termos, velas, pelucas, etc.)",
    "371000 Reciclamiento de desperdicios y desechos metálicos",
    "372000 Reciclamiento de desperdicios y desechos no metálicos",
    "401110 Generación de energía térmica convencional(Incluye la producción de energía eléctricamediante máquinasturbo-gas, turbo vapor, ciclo combinado y turbo diesel)",
    "401120 Generación de energía térmica nuclear(Incluye la producción de energía eléctrica mediante combustiblenuclear)",
    "401130 Generación de energía hidráulica(Incluye la producción de energía eléctrica mediante centrales de bombeo)",
    "401190 Generación de energía n.c.p.(Incluye la producción de energía eléctrica mediante fuentes de energía solar, biomasa, eólica, geotérmica, mareomotriz, etc.)",
    "401200 Transporte de energía eléctrica",
    "401300 Distribución de energía eléctrica",
    "402001 Fabricación y distribución de gas(No incluye el transporte por gasoductos)",
    "402009 Fabricación y distribución de combustibles gaseosos n.c.p.",
    "403000 Suministro de vapor y agua caliente",
    "410010 Captación, depuración y distribución de agua de fuentes subterráneas",
    "410020 Captación, depuración y distribución de agua de fuentes superficiales",
    "451100 Demolición y voladura de edificios y de sus partes(Incluye los trabajos de limpieza deescombros asociados a la demolición y voladura, las perforaciones asociadas a la preparación del terreno para la construcción de obras, la limpieza del terreno de maleza",
    "451200 Perforación y sondeo excepto: perforación de pozos de petróleo, de gas, de minas e hidráulicos y prospección de yacimientos de petróleo(Incluye los trabajos de perforación, sondeo y muestreo con fines de construcción o para estudios geofísicos, geológico",
    "451900 Movimiento de suelos y preparación de terrenos para obras n.c.p.(Incluye el drenaje, remoción de rocas,excavación de zanjas para servicios públicos, alcantarillado urbano y para construcciones diversas, movimientos de tierras para hacer terraplenes o desm",
    "452100 Construcción, reforma y reparación de edificios residenciales(Incluye la construcción,reforma y reparación de viviendas unifamiliares y multifamiliares; bungalows, cabañas, casas de campo, departamentos, albergues para ancianos, niños, estudiantes, etc.)",
    "452200 Construcción, reforma y reparación de edificios no residenciales(Incluye construcción,reforma y reparación de restaurantes, bares, campamentos, bancos, oficinas, galerías comerciales, estaciones de servicio, edificios para tráfico y comunicaciones, garaje",
    "452310 Construcción, reforma y reparación de obras hidráulicas(Incluye obras fluviales y canales, acueductos, diques, etc.)",
    "452390 Construcción, reforma y reparación de obras de infraestructura del transporte n.c.p(Incluye la construcción, reforma y reparación de calles, autopistas, carreteras, puentes, túneles, vías férreas y pistas de aterrizaje, la señalización mediante pintura, e",
    "452400 Construcción, reforma y reparación de redes(Incluye la construcción, reforma y reparación de redes de electricidad, de gas, de agua, de telecomunicaciones, etc.)",
    "452510 Perforación de pozos de agua",
    "452520 Actividades de hincado de pilotes, cimentación y otros trabajos de hormigón armado",
    "452590 Actividades especializadas de construcción n.c.p.(Incluye el alquiler e instalación deandamios, laconstrucción de chimeneas y hornos industriales, el acorazamiento de cajas fuertes y cámaras frigoríficas, el armado e instalación de compuertas para diques",
    "452900 Obras de ingeniería civil n.c.p.(Incluye los trabajos generales de construcción para la minería y laindustria, de centrales eléctricas y nucleares, excavaciones de sepulturas, etc.)",
    "453110 Instalaciones de ascensores, montacargas y escaleras mecánicas",
    "453120 Instalación de sistemas de iluminación, control y señalización eléctrica para el transporte",
    "453190 Ejecución y mantenimiento de instalaciones eléctricas y electrónicas n.c.p.(Incluye lainstalación deantenas, pararrayos, sistemas de alarmas contra incendios y robos, sistemas de telecomunicación, etc.)",
    "453200 Aislamiento térmico, acústico, hídrico y antivibratorio",
    "453300 Instalaciones de gas, agua, sanitarios y de climatización, con sus artefactos conexos(Incluye la instalación de compactadores, calderas, sistemas de calefacción central, etc.)",
    "453900 Instalaciones para edificios y obras de ingeniería civil n.c.p.",
    "454100 Instalaciones de carpintería, herrería de obra y artística(Incluye instalación de puertas y ventanas,carpintería metálica y no metálica, etc.)",
    "454200 Terminación y revestimiento de paredes y pisos(Incluye yesería, salpicré, el pulido depisos y la colocación de revestimientos de cerámicas, de piedra tallada, de suelos flexibles, parqué , baldosas, empapelados, etc.)",
    "454300 Colocación de cristales en obra(Incluye la instalación y revestimiento de vidrio, espejos y otros artículos de vidrio, etc.)",
    "454400 Pintura y trabajos de decoración",
    "454900 Terminación de edificios y obras de ingeniería civil n.c.p.(Incluye trabajos de ornamentación, limpiezaexterior de edificios con vapor, chorro de arena u otros métodos, etc.)",
    "455000 Alquiler de equipo de construcción o demolición dotado de operarios",
    "501110 Venta de autos, camionetas y utilitarios, nuevos(Incluye taxis, jeeps, 4x4 y vehículossimilares)",
    "501190 Venta de vehículos automotores, nuevos n.c.p.(Incluye casas rodantes, trailers, camiones, remolques,ambulancias, ómnibus, microbuses y similares, cabezas tractoras, etc.)",
    "501210 Venta de autos, camionetas y utilitarios, usados(Incluye taxis, jeeps, 4x4 y vehículossimilares)",
    "501290 Venta de vehículos automotores, usados n.c.p.(Incluye, casas rodantes, trailers, camiones, remolques,ambulancias, ómnibus, microbuses y similares, cabezas tractoras, etc..)",
    "502100 Lavado automático y manual",
    "502210 Reparación de cámaras y cubiertas(Incluye reparación de llantas)",
    "502220 Reparación de amortiguadores, alineación de dirección y balanceo de ruedas",
    "502300 Instalación y reparación de lunetas y ventanillas, alarmas, cerraduras, radios, sistemas de climatización automotor y grabado de cristales(Incluye instalación y reparación de parabrisas, aletas, burletes, colisas, levantavidrios, parlantes y autoestereos",
    "502400 Tapizado y retapizado",
    "502500 Reparaciones eléctricas, del tablero e instrumental; reparación y recarga de baterías",
    "502600 Reparación y pintura de carrocerías; colocación de guardabarros y protecciones exteriores",
    "502910 Instalación y reparación de caños de escape",
    "502920 Mantenimiento y reparación de frenos",
    "502990 Mantenimiento y reparación del motor n.c.p.; mecánica integral(Incluye auxilio y servicios de grúa paraautomotores; instalación y reparación de equipos de GNC)",
    "503100 Venta al por mayor de partes, piezas y accesorios de vehículos automotores",
    "503210 Venta al por menor de cámaras y cubiertas",
    "503220 Venta al por menor de baterías",
    "503290 Venta al por menor de partes, piezas y accesorios excepto cámaras, cubiertas y baterías",
    "504010 Venta de motocicletas y de sus partes, piezas y accesorios",
    "504020 Mantenimiento y reparación de motocicletas",
    "505000 Venta al por menor de combustible para vehículos automotores y motocicletas(Incluye estaciones de servicios y la venta al por menor de productos lubricantes y refrigerantes para automotores y motocicletas)",
    "511111 Venta al por mayor en comisión o consignación de cereales (incluye arroz), oleaginosasy forrajeras excepto semillas",
    "511112 Venta al por mayor en comisión o consignación de semillas",
    "511119 Venta al por mayor en comisión o consignación de productos agrícolas n.c.p.",
    "511121 Operaciones de intermediación de ganado en pie(Incluye consignatarios de hacienda y ferieros)",
    "511122 Operaciones de intermediación de lanas, cueros y productos afines de terceros",
    "511911 Operaciones de intermediación de carne - consignatario directo -",
    "511912 Operaciones de intermediación de carne excepto consignatario directo(Incluye consignatarios y abastecedores de carnes, etc.)",
    "511919 Venta al por mayor en comisión o consignación de alimentos, bebidas y tabaco n.c.p.",
    "511920 Venta al por mayor en comisión o consignación de productos textiles, prendas de vestir,calzado excepto el ortopédico, artículos de marroquinería, paraguas y simi",
    "511930 Venta al por mayor en comisión o consignación de madera y materiales para la construcción",
    "511940 Venta al por mayor en comisión o consignación de energía eléctrica, gas y combustibles",
    "511950 Venta al por mayor en comisión o consignación de minerales, metales y productos químicos industriales",
    "511960 Venta al por mayor en comisión o consignación de maquinaria, equipo profesional industrial y comercial,embarcaciones y aeronaves",
    "511970 Venta al por mayor en comisión o consignación de papel, cartón, libros, revistas, diarios, materialesdeembalaje y artículos de librería",
    "511990 Venta al por mayor en comisión o consignación de mercaderías n.c.p.(Incluye galeríasde arte)",
    "512111 Venta al por mayor de cereales (incluye arroz), oleaginosas y forrajeras excepto semillas",
    "512112 Venta al por mayor de semillas",
    "512119 Venta al por mayor de materias primas agrícolas y de la silvicultura n.c.p.(Incluye elacopio y ventaalpor mayor de frutas, flores y plantas, etc.)",
    "512121 Venta al por mayor de lanas, cueros en bruto y productos afines",
    "512129 Venta al por mayor de materias primas pecuarias incluso animales vivos n.c.p.",
    "512211 Venta al por mayor de productos lácteos",
    "512212 Venta al por mayor de fiambres y quesos",
    "512221 Venta al por mayor de carnes y derivados excepto las de aves.",
    "512229 Venta al por mayor de aves, huevos y productos de granja y de la caza n.c.p.",
    "512230 Venta al por mayor de pescado",
    "512240 Venta al por mayor y empaque de frutas, de legumbres y hortalizas frescas(Incluye la conservación encámaras frigoríficas por parte de los empaquetadores)",
    "512250 Venta al por mayor de pan, productos de confitería y pastas frescas",
    "512260 Venta al por mayor de chocolates, golosinas y productos para kioscos y polirrubros n.c.p., excepto cigarrillos",
    "512271 Venta al por mayor de azúcar",
    "512272 Venta al por mayor de aceites y grasas",
    "512273 Venta al por mayor de café, té, yerba mate y otras infusiones y especias y condimentos(Incluye la ventade sal, etc.)",
    "512279 Venta al por mayor de productos y subproductos de molinería n.c.p.",
    "512291 Venta al por mayor de frutas, legumbres y cereales secos y en conserva",
    "512292 Venta al por mayor de alimentos para animales",
    "512299 Venta al por mayor de productos alimenticios n.c.p.(Incluye la venta de miel y derivados, productos congelados, etc.)",
    "512311 Venta al por mayor de vino",
    "512312 Venta al por mayor de bebidas espiritosas",
    "512319 Venta al por mayor de bebidas alcohólicas n.c.p.(Incluye la venta de aperitivos con alcohol, cerveza,sidra, el fraccionamiento de alcohol, etc.)",
    "512320 Venta al por mayor de bebidas no alcohólicas(Incluye la venta de aguas, sodas, bebidasrefrescantes,jarabes, extractos, concentrados, gaseosas, jugos, etc.)",
    "512400 Venta al por mayor de cigarrillos y productos de tabaco",
    "513111 Venta al por mayor de productos textiles excepto telas, tejidos, prendas y accesorios de vestir(Incluyefibras vegetales, animales, minerales y manufacturadas)",
    "513112 Venta al por mayor de tejidos (telas)",
    "513113 Venta al por mayor de artículos de mercería(Incluye la venta de puntillas, galones, hombreras, agujas, botones, etc.)",
    "513114 Venta al por mayor de mantelería, ropa de cama y artículos textiles para el hogar",
    "513115 Venta al por mayor de tapices y alfombras de materiales textiles",
    "513121 Venta al por mayor de prendas de vestir de cuero",
    "513122 Venta al por mayor de medias y prendas de punto",
    "513129 Venta al por mayor de prendas de vestir n.c.p.",
    "513130 Venta al por mayor de calzado excepto el ortopédico(Incluye venta de calzado de cuero,tela, plástico, goma, etc.)",
    "513141 Venta al por mayor de pieles y cueros curtidos y salados",
    "513142 Venta al por mayor de suelas y afines(Incluye talabarterías, artículos regionales de cuero, almacenesdesuelas, etc.)",
    "513149 Venta al por mayor de artículos de marroquinería, paraguas y productos similares n.c.p.",
    "513211 Venta al por mayor de libros y publicaciones",
    "513212 Venta al por mayor de diarios y revistas",
    "513221 Venta al por mayor de papel y productos de papel y cartón excepto envases",
    "513222 Venta al por mayor de envases de papel y cartón",
    "513223 Venta al por mayor de artículos de librería y papelería",
    "513310 Venta al por mayor de productos farmacéuticos y veterinarios(Incluye venta de medicamentos y kits dediagnóstico como test de embarazo, hemoglucotest, vacunas, etc.)",
    "513320 Venta al por mayor de productos cosméticos, de tocador y de perfumería",
    "513330 Venta al por mayor de instrumental médico y odontológico y artículos ortopédicos(Incluye venta de vaporizadores, nebulizadores, masajeadores, termómetros, prótesis, muletas, plantillas, calzado ortopédico y otros artículos similares de uso personal o domé",
    "513410 Venta al por mayor de artículos de óptica y de fotografía(Incluye venta de lentes de contacto, líquidosoftalmológicos, armazones, cristales ópticos, películas fotográficas, cámaras y accesorios para fotografía, etc.)",
    "513420 Venta al por mayor de artículos de relojería, joyería y fantasías",
    "513511 Venta al por mayor de muebles metálicos excepto de oficina",
    "513519 Venta al por mayor de muebles n.c.p. excepto de oficina; artículos de mimbre y corcho;colchones y somieres",
    "513520 Venta al por mayor de artículos de iluminación",
    "513531 Venta al por mayor de artículos de vidrio",
    "513532 Venta al por mayor de artículos de bazar y menaje excepto de vidrio",
    "513540 Venta al por mayor de artefactos para el hogar, eléctricos, a gas, kerosene u otros combustibles(Incluyeelectrodomésticos, cocinas, estufas y salamandras, hornos, etc., excepto equipos de sonido, televisión y video)",
    "513551 Venta al por mayor de instrumentos musicales, discos y casetes de audio y video, etc.",
    "513552 Venta al por mayor de equipos de sonido, radio y televisión, comunicaciones y sus componentes, repuestosy accesorios",
    "513910 Venta al por mayor de materiales y productos de limpieza",
    "513920 Venta al por mayor de juguetes(Incluye artículos de cotillón)",
    "513930 Venta al por mayor de bicicletas y rodados similares(Incluye cochecitos y sillas de paseo para bebés,andadores, triciclos, etc.)",
    "513940 Venta al por mayor de artículos de esparcimiento y deportes(Incluye embarcaciones deportivas, armas ymuniciones, equipos de pesca, piletas de natación de lona o plástico, etc.)",
    "513950 Venta al por mayor de papeles para pared, revestimiento para pisos de goma, plástico ytextiles, y artículos similares para la decoración",
    "513991 Venta al por mayor de flores y plantas naturales y artificiales",
    "513992 Venta al por mayor de productos en general en almacenes y supermercados mayoristas, conpredominio dealimentos y bebidas",
    "513999 Venta al por mayor de artículos de uso doméstico y/o personal n.c.p(Incluye artículosde platería excepto los incluidos en talabartería, cuadros y marcos que no sean obra de arte o de colección, sahumerios y artículos de santería, parrillas y hogares, etc.",
    "514110 Venta al por mayor de combustibles y lubricantes para automotores",
    "514191 Fraccionamiento y distribución de gas licuado",
    "514199 Venta al por mayor de combustibles y lubricantes, excepto para automotores, leña y carbón",
    "514200 Venta al por mayor de metales y minerales metalíferos",
    "514310 Venta al por mayor de aberturas(Incluye puertas, ventanas, cortinas de enrollar de PVC, madera, aluminio, puertas corredizas, frentes de placards, etc.)",
    "514320 Venta al por mayor de productos de madera excepto muebles(Incluye placas, varillas, parqué, machimbre, etc.)",
    "514330 Venta al por mayor de artículos de ferretería",
    "514340 Venta al por mayor de pinturas y productos conexos",
    "514350 Venta al por mayor de vidrios planos y templados",
    "514391 Venta al por mayor de artículos de plomería, electricidad, calefacción, obras sanitarias, etc.",
    "514392 Venta al por mayor de artículos de loza, cerámica y porcelana de uso en construcción",
    "514399 Venta al por mayor de ladrillos, cemento, cal, arena, piedra, mármol y materiales parala construcciónn.c.p.",
    "514910 Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos textiles",
    "514920 Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos de papel ycartón",
    "514931 Venta al por mayor de abonos, fertilizantes y plaguicidas",
    "514932 Venta al por mayor de caucho y productos de caucho excepto calzado y autopartes",
    "514933 Venta al por mayor de artículos de plástico",
    "514940 Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos metálicos(Incluye chatarra,viruta de metales diversos, etc.)",
    "514990 Venta al por mayor de productos intermedios, desperdicios y desechos n.c.p.(Incluye venta al por mayor de petróleo, minerales no metalíferos, etc.)",
    "515110 Venta al por mayor de máquinas, equipos e implementos de uso en los sectores agropecuario, jardinería,silvicultura, pesca y caza(Incluye venta de tractores, cosechadoras, enfardadoras, remolques de carga y descarga automática, motosierras, cortadoras de c",
    "515120 Venta al por mayor de máquinas, equipos e implementos de uso en la elaboración de alimentos, bebidas ytabacos(Incluye máquinas para moler, picar y cocer alimentos, fabricadora de pastas, bateas, enfriadoras y envasadoras de bebidas, etc.)",
    "515130 Venta al por mayor de máquinas, equipos e implementos de uso en la fabricación de textiles, prendas yaccesorios de vestir, calzado, artículos de cuero y marroquin(Incluye venta de máquinas de coser, de cortar tejidos, de tejer, extender telas, robots de c",
    "515140 Venta al por mayor de máquinas, equipos e implementos de uso en imprentas, artes gráficas y actividades conexas(Incluye venta de máquinas fotocopiadoras - excepto las de uso personal- copiadoras de planos, máquinas para imprimir, guillotinar, troquelar, e",
    "515150 Venta al por mayor de máquinas, equipos e implementos de uso médico y paramédico(Incluye venta de equipos de diagnóstico y tratamiento, camillas, cajas de cirugía, jeringas y otros implementos de material descartable, etc.)",
    "515160 Venta al por mayor de máquinas, equipos e implementos de uso en la industria del plástico y del caucho(Incluye sopladora de envases, laminadora de plásticos, máquinas extrusoras y moldeadoras, etc.)",
    "515190 Venta al por mayor de máquinas, equipos e implementos de uso especial n.c.p.(Incluye motoniveladoras,excavadoras, palas mecánicas, perforadoras-percutoras, etc.)",
    "515200 Venta al por mayor de máquinas - herramienta de uso general",
    "515300 Venta al por mayor de vehículos, equipos y máquinas para el transporte ferroviario, aéreo y de navegación",
    "515410 Venta al por mayor de muebles e instalaciones para oficinas",
    "515420 Venta al por mayor de muebles e instalaciones para la industria, el comercio y los servicios n.c.p.",
    "515910 Venta al por mayor de equipo profesional y científico e instrumentos de medida y de control",
    "515921 Venta al por mayor de equipos informáticos y máquinas electrónicas de escribir y calcular(Incluye laventa de computadoras incluso las portátiles y sus periféricos, impresoras, suministros para computación, software, máquinas de escribir y calcular electró",
    "515922 Venta al por mayor de máquinas y equipos de comunicaciones, control y seguridad(Incluye venta de productos de telefonía, equipos de circuito cerrado, sistemas de alarmas y sirenas contra incendios, robos y otros sistemas de seguridad, equipos de facsímil,",
    "515990 Venta al por mayor de máquinas, equipo y materiales conexos n.c.p.(Incluye máquinas registradoras deescribir y de calcular mecánicas, equipos para destruir documentos, etc.)",
    "519000 Venta al por mayor de mercancías n.c.p.",
    "521110 Venta al por menor en hipermercados con predominio de productos alimentarios y bebidas",
    "521120 Venta al por menor en supermercados con predominio de productos alimentarios y bebidas",
    "521130 Venta al por menor en minimercados con predominio de productos alimentarios y bebidas",
    "521190 Venta al por menor en kioscos, polirrubros y comercios no especializados n.c.p.",
    "521200 Venta al por menor excepto la especializada, sin predominio de productos alimentarios ybebidas",
    "522111 Venta al por menor de productos lácteos",
    "522112 Venta al por menor de fiambres y embutidos",
    "522120 Venta al por menor de productos de almacén y dietética",
    "522210 Venta al por menor de carnes rojas, menudencias y chacinados frescos",
    "522220 Venta al por menor de huevos, carne de aves y productos de granja y de la caza n.c.p.",
    "522300 Venta al por menor de frutas, legumbres y hortalizas frescas",
    "522410 Venta al por menor de pan y productos de panadería",
    "522420 Venta al por menor de bombones, golosinas y demás productos de confitería",
    "522500 Venta al por menor de bebidas",
    "522910 Venta al por menor de pescados y productos de la pesca",
    "522991 Venta al por menor de tabaco y sus productos",
    "522999 Venta al por menor de productos alimentarios n.c.p., en comercios especializados",
    "523110 Venta al por menor de productos farmacéuticos y de herboristería",
    "523120 Venta al por menor de productos cosméticos, de tocador y de perfumería",
    "523130 Venta al por menor de instrumental médico y odontológico y artículos ortopédicos(Incluye venta de vaporizadores, nebulizadores, masajeadores, termómetros, prótesis, muletas, plantillas, calzado ortopédico y otros artículos similares de uso personal o domé",
    "523210 Venta al por menor de hilados, tejidos y artículos de mercería(Incluye mercerías, sederías, comerciosdeventa de lanas y otros hilados, etc.)",
    "523220 Venta al por menor de confecciones para el hogar(Incluye la venta al por menor de sábanas, toallas, mantelería, cortinas confeccionadas, colchas, cubrecamas, etc.)",
    "523290 Venta al por menor de artículos textiles n.c.p. excepto prendas de vestir(Incluye la venta al por menorde tapices, alfombras, etc.)",
    "523310 Venta al por menor de ropa interior, medias, prendas para dormir y para la playa(Incluye corsetería,lencería, camisetas, medias excepto ortopédicas, pijamas, camisones y saltos de cama, salidas de baño, trajes de baño, etc.)",
    "523320 Venta al por menor de indumentaria de trabajo, uniformes y guardapolvos",
    "523330 Venta al por menor de indumentaria para bebés y niños",
    "523391 Venta al por menor de prendas de vestir de cuero y sucedáneos excepto calzado",
    "523399 Venta al por menor de prendas y accesorios de vestir n.c.p. excepto calzado, artículosde marroquinería,paraguas y similares",
    "523410 Venta al por menor de artículos regionales y de talabartería(Incluye venta de artículos de talabarteríay regionales de cuero, plata, alpaca y similares)",
    "523420 Venta al por menor de calzado excepto el ortopédico",
    "523490 Venta al por menor de artículos de marroquinería, paraguas y similares n.c.p.",
    "523510 Venta al por menor de muebles excepto de oficina, la industria, el comercio y los servicios; artículosdemimbre y corcho",
    "523520 Venta al por menor de colchones y somieres",
    "523530 Venta al por menor de artículos de iluminación",
    "523540 Venta al por menor de artículos de bazar y menaje",
    "523550 Venta al por menor de artefactos para el hogar, eléctricos, a gas, a kerosene u otroscombustibles(Incluye electrodomésticos -excepto equipos de sonido-, televisión y video, cocinas, estufas, hornos, etc.)",
    "523560 Venta al por menor de instrumentos musicales, equipos de sonido, casetes de audio y video, discos de audio y video",
    "523590 Venta al por menor de artículos para el hogar n.c.p.",
    "523610 Venta al por menor de aberturas(Incluye puertas, ventanas, cortinas de enrollar de PVC, madera, aluminio, puertas corredizas, frentes de placards, etc.)",
    "523620 Venta al por menor de maderas y artículos de madera y corcho excepto muebles",
    "523630 Venta al por menor de artículos de ferretería",
    "523640 Venta al por menor de pinturas y productos conexos",
    "523650 Venta al por menor de artículos para plomería e instalación de gas",
    "523660 Venta al por menor de cristales, espejos, mamparas y cerramientos",
    "523670 Venta al por menor de papeles para pared, revestimientos para pisos y artículos similares para la decoración",
    "523690 Venta al por menor de materiales de construcción n.c.p.",
    "523710 Venta al por menor de artículos de óptica y fotografía",
    "523720 Venta al por menor de artículos de relojería, joyería y fantasía",
    "523810 Venta al por menor de libros y publicaciones",
    "523820 Venta al por menor de diarios y revistas",
    "523830 Venta al por menor de papel, cartón, materiales de embalaje y artículos de librería",
    "523911 Venta al por menor de flores y plantas naturales y artificiales",
    "523912 Venta al por menor de semillas, abonos, fertilizantes y otros productos de vivero",
    "523920 Venta al por menor de materiales y productos de limpieza",
    "523930 Venta al por menor de juguetes y artículos de cotillón",
    "523941 Venta al por menor de artículos de deporte, equipos e indumentaria deportiva",
    "523942 Venta al por menor de armas y artículos de cuchillería, artículos para la caza y pesca",
    "523950 Venta al por menor de máquinas y equipos para oficina y sus componentes y repuestos",
    "523960 Venta al por menor de fuel oil, gas en garrafas, carbón y leña(No incluye las estaciones de serviciosque se clasifican en 505000)",
    "523970 Venta al por menor de productos veterinarios y animales domésticos",
    "523991 Venta al por menor de artículos de caucho excepto cámaras y cubiertas",
    "523992 Venta al por menor de máquinas y motores y sus repuestos",
    "523993 Venta al por menor de equipo profesional y científico e instrumentos de medida y de control",
    "523994 Venta al por menor de artículos de colección y objetos de arte",
    "523999 Venta al por menor de artículos nuevos n.c.p.(Incluye casas de regalos, de artesaníasy artículos regionales excepto de talabartería, de artículos religiosos, de monedas y sellos, etc.)",
    "524100 Venta al por menor de muebles usados",
    "524200 Venta al por menor de libros, revistas y similares usados",
    "524910 Venta al por menor de antigüedades(Incluye venta de antigüedades en remates)",
    "524990 Venta al por menor de artículos usados n.c.p. excluidos automotores y motocicletas",
    "525100 Venta al por menor por correo, televisión, internet y otros medios de comunicación",
    "525200 Venta al por menor en puestos móviles",
    "525900 Venta al por menor no realizada en establecimientos n.c.p.(Incluye venta mediante máquinas expendedoras, vendedores ambulantes y vendedores a domicilio)",
    "526100 Reparación de calzado y artículos de marroquinería",
    "526200 Reparación de artículos eléctricos de uso doméstico",
    "526901 Reparación de relojes y joyas",
    "526909 Reparación de artículos n.c.p.",
    "551100 Servicios de alojamiento en camping(Incluye refugios de montaña)",
    "551210 Servicios de alojamiento por hora",
    "551221 Servicios de alojamiento en pensiones",
    "551222 Servicios de alojamiento en hoteles, hosterías y residenciales similares, excepto por hora, que incluyenservicio de restaurante al público",
    "551223 Servicios de alojamiento en hoteles, hosterías y residenciales similares, excepto por hora, que no incluyen servicio de restaurante al público",
    "551229 Servicios de hospedaje temporal n.c.p.(Incluye hospedaje en estancias, residencias para estudiantes yalbergues juveniles, apartamentos turísticos, etc.)",
    "552111 Servicios de restaurantes y cantinas sin espectáculo",
    "552112 Servicios de restaurantes y cantinas con espectáculo",
    "552113 Servicios de pizzerías, fast food y locales de venta de comidas y bebidas al paso(Incluye el expendiode pizza, empanadas, hamburguesas, productos lácteos excepto helados, etc.)",
    "552114 Servicios de bares y confiterías(Incluye locales de expendio de bebidas con servicio de mesa y/o de mostrador para consumo en el lugar, salones de té, servicios de comedores escolares, cantinas deportivas, fábricas etc.)",
    "552119 Servicios de expendio de comidas y bebidas en establecimientos con servicio de mesa y/oen mostrador -excepto en heladerías - n.c.p.",
    "552120 Expendio de helados",
    "552210 Provisión de comidas preparadas para empresas(Incluye el servicio de catering, el suministro de comidaspara banquetes, bodas, fiestas y otras celebraciones, etc.)",
    "552290 Preparación y venta de comidas para llevar n.c.p.(Incluye casas de comidas, rotiseríasy demás lugares que no poseen espacio para el consumo in situ)",
    "601100 Servicio de transporte ferroviario de cargas",
    "601210 Servicio de transporte ferroviario urbano y suburbano de pasajeros(Incluye el serviciode subterráneoyde premetro)",
    "601220 Servicio de transporte ferroviario interurbano de pasajeros",
    "602110 Servicios de mudanza(Incluye servicios de guardamuebles)",
    "602120 Servicios de transporte de mercaderías a granel, incluido el transporte por camión cisterna",
    "602130 Servicios de transporte de animales",
    "602180 Servicio de transporte urbano de carga n.c.p.(Incluye el transporte realizado por fleteros y distribuidores dentro del égido urbano)",
    "602190 Transporte automotor de cargas n.c.p.(Incluye servicios de transporte de carga refrigerada, automotores, transporte pesado y de mercaderías peligrosas)",
    "602210 Servicio de transporte automotor urbano regular de pasajeros(Incluye los servicios detransporte regularde menos de 50 km.)",
    "602220 Servicios de transporte automotor de pasajeros mediante taxis y remises; alquiler de autos con chofer",
    "602230 Servicio de transporte escolar(Incluye el sevicio de transporte para colonias de vacaciones y clubes)",
    "602240 Servicio de transporte automotor urbano de oferta libre de pasajeros excepto mediantetaxis y remises, alquiler de autos con chofer y transporte escolar(Incluye servicios urbanos especiales como charters, servicios contratados, servicios para ámbito portu",
    "602250 Servicio de transporte automotor interurbano de pasajeros(Incluye los servicios de transporte regulardemás de 50 km., los llamados servicios de larga distancia)",
    "602260 Servicio de transporte automotor de pasajeros para el turismo",
    "602290 Servicio de transporte automotor de pasajeros n.c.p.",
    "603100 Servicio de transporte por oleoductos y poliductos",
    "603200 Servicio de transporte por gasoductos",
    "611100 Servicio de transporte marítimo de carga",
    "611200 Servicio de transporte marítimo de pasajeros",
    "612100 Servicio de transporte fluvial de cargas",
    "612200 Servicio de transporte fluvial de pasajeros",
    "621000 Servicio de transporte aéreo de cargas",
    "622000 Servicio de transporte aéreo de pasajeros",
    "631000 Servicios de manipulación de carga(Incluye los servicios de carga y descarga de mercancías o equipajes de pasajeros, sin discriminar medios de transporte, la estiba y desestiba, etc.)",
    "632000 Servicios de almacenamiento y depósito(Incluye silos de granos, depósitos con cámarasfrigoríficas, almacenes para mercancías diversas, incluso productos de zona franca, etc.)",
    "633110 Servicios de explotación de infraestructura para el transporte terrestre; peajes y otros derechos",
    "633120 Servicios prestados por playas de estacionamiento y garajes",
    "633190 Servicios complementarios para el transporte terrestre n.c.p.(Incluye servicios de mantenimiento de material ferroviario, terminales y estaciones)",
    "633210 Servicios de explotación de infraestructura para el transporte por agua; derechos de puerto",
    "633220 Servicios de guarderías náuticas",
    "633230 Servicios para la navegación(Incluye servicios de practicaje y pilotaje, atraque y salvamento)",
    "633290 Servicios complementarios para el transporte por agua n.c.p.(Incluye explotación de servicios de terminales como puertos y muelles)",
    "633310 Servicios de hangares, estacionamiento y remolque de aeronaves",
    "633320 Servicios para la aeronavegación(Incluye servicios de terminales como aeropuertos, actividades de control de tráfico aéreo, etc.)",
    "633390 Servicios complementarios para el transporte aéreo n.c.p.(Incluye servicios de prevención y extincióndeincendios)",
    "634100 Servicios mayoristas de agencias de viajes",
    "634200 Servicios minoristas de agencias de viajes",
    "634300 Servicios complementarios de apoyo turístico",
    "635000 Servicios de gestión y logística para el transporte de mercaderías(Incluye las actividades de los agentes aduaneros, actividades de empresas empaquetadoras, etc.)",
    "641000 Servicios de correos",
    "642010 Servicios de transmisión de radio y televisión",
    "642020 Servicios de comunicación por medio de teléfono, telégrafo y télex",
    "642091 Emisión de programas de televisión",
    "642099 Servicios de transmisión n.c.p. de sonido, imágenes, datos u otra información",
    "651100 Servicios de la banca central(Incluye las actividades del Banco Central de la República Argentina)",
    "652110 Servicios de la banca mayorista",
    "652120 Servicios de la banca de inversión",
    "652130 Servicios de la banca minorista",
    "652201 Servicios de intermediación financiera realizada por las compañías financieras",
    "652202 Servicios de intermediación financiera realizada por sociedades de ahorro y préstamo para la vivienday otros inmuebles",
    "652203 Servicios de intermediación financiera realizada por cajas de crédito",
    "659810 Actividades de crédito para financiar otras actividades económicas(Incluye las empresas de factoringy otras formas de adelanto, etc.)",
    "659890 Servicios de crédito n.c.p.(Incluye el otorgamiento de préstamos por entidades que noreciben depósitosy que están fuera del sistema bancario, y cuyo destino es financiar el consumo, la vivienda u otros bienes)",
    "659910 Servicios de agentes de mercado abierto puros(Incluye las transacciones extrabursátiles - por cuenta propia -)",
    "659920 Servicios de entidades de tarjeta de compra y/o crédito",
    "659990 Servicios de financiación y actividades financieras n.c.p.(Incluye actividades de inversión en acciones,títulos, fondos comunes de inversión, la actividad de corredores de bolsa, las sociedades de inversión inmobiliaria y sociedades de cartera, arrenda",
    "661110 Servicios de seguros de salud(Incluye medicina prepaga)",
    "661120 Servicios de seguros de vida(Incluye los seguros de vida, retiro y sepelio)",
    "661130 Servicios de seguros a las personas excepto los de salud y de vida(Incluye los seguros de accidentes)",
    "661210 Servicios de aseguradoras de riesgo de trabajo (A.R.T.)",
    "661220 Servicios de seguros patrimoniales excepto los de las aseguradoras de riesgo de trabajo",
    "661300 Reaseguros",
    "662000 Administración de fondos de jubilaciones y pensiones (A.F.J.P.)",
    "671110 Servicios de mercados y cajas de valores",
    "671120 Servicios de mercados a término",
    "671130 Servicios de bolsas de Comercio",
    "671200 Servicios bursátiles de mediación o por cuenta de terceros(Incluye la actividad de agentes y sociedadesde bolsa)",
    "671910 Servicios de casas y agencias de cambio",
    "671920 Servicios de sociedades calificadoras de riesgos",
    "671990 Servicios auxiliares a la intermediación financiera n.c.p., excepto a los servicios deseguros y de administración de fondos de jubilaciones y pensiones",
    "672110 Servicios de productores y asesores de seguros",
    "672190 Servicios auxiliares a los servicios de seguros n.c.p.",
    "672200 Servicios auxiliares a la administración de fondos de jubilaciones y pensiones",
    "701010 Servicios de alquiler y explotación de inmuebles para fiestas, convenciones y otros eventos similares",
    "701090 Servicios inmobiliarios realizados por cuenta propia, con bienes propios o arrendados n.c.p.",
    "702000 Servicios inmobiliarios realizados a cambio de una retribución o por contrata(Incluyecompra, venta,alquiler, remate, tasación, administración de bienes, etc., realizados a cambio de una retribución o por contrata, y la actividad de administradores, martil",
    "711100 Alquiler de equipo de transporte para vía terrestre, sin operarios ni tripulación",
    "711200 Alquiler de equipo de transporte para vía acuática, sin operarios ni tripulación",
    "711300 Alquiler de equipo de transporte para vía aérea, sin operarios ni tripulación",
    "712100 Alquiler de maquinaria y equipo agropecuario, sin operarios",
    "712200 Alquiler de maquinaria y equipo de construcción e ingeniería civil, sin operarios(Incluye el alquilerdeandamios sin montaje ni desmantelamiento)",
    "712300 Alquiler de maquinaria y equipo de oficina, incluso computadoras",
    "712901 Alquiler de maquinaria y equipo para la industria manufacturera, sin personal",
    "712902 Alquiler de maquinaria y equipo minero y petrolero, sin personal",
    "712909 Alquiler de maquinaria y equipo n.c.p., sin personal",
    "713001 Alquiler de ropa",
    "713009 Alquiler de efectos personales y enseres domésticos n.c.p.(Incluye alquiler de artículos deportivos ydevideos)",
    "721000 Servicios de consultores en equipo de informática",
    "722000 Servicios de consultores en informática y suministros de programas de informática",
    "723000 Procesamiento de datos",
    "724000 Servicios relacionados con bases de datos",
    "725000 Mantenimiento y reparación de maquinaria de oficina, contabilidad e informática",
    "729000 Actividades de informática n.c.p.",
    "731100 Investigación y desarrollo experimental en el campo de la ingeniería y la tecnología",
    "731200 Investigación y desarrollo experimental en el campo de las ciencias médicas",
    "731300 Investigación y desarrollo experimental en el campo de las ciencias agropecuarias",
    "731900 Investigación y desarrollo experimental en el campo de las ciencias exactas y naturales n.c.p.",
    "732100 Investigación y desarrollo experimental en el campo de las ciencias sociales",
    "732200 Investigación y desarrollo experimental en el campo de las ciencias humanas",
    "741101 Servicios jurídicos",
    "741102 Servicios notariales",
    "741200 Servicios de contabilidad y teneduría de libros, auditoría y asesoría fiscal",
    "741300 Estudio de mercado, realización de encuestas de opinión pública",
    "741401 Servicios de asesoramiento, dirección y gestión empresarial realizados por integrantesde los órganosdeadministración y/o fiscalización en sociedades anónimas",
    "741402 Servicios de asesoramiento, dirección y gestión empresarial realizados por integrantesde cuerpos de dirección en sociedades excepto las anónimas",
    "741409 Servicios de asesoramiento, dirección y gestión empresarial n.c.p.",
    "742101 Servicios relacionados con la construcción.(Incluye los servicios prestados por ingenieros, arquitectosy técnicos)",
    "742102 Servicios geológicos y de prospección",
    "742103 Servicios relacionados con la electrónica y las comunicaciones",
    "742109 Servicios de arquitectura e ingeniería y servicios conexos de asesoramiento técnico n.c.p.",
    "742200 Ensayos y análisis técnicos",
    "743000 Servicios de publicidad",
    "749100 Obtención y dotación de personal",
    "749210 Servicios de transporte de caudales y objetos de valor",
    "749290 Servicios de investigación y seguridad n.c.p.",
    "749300 Servicios de limpieza de edificios",
    "749400 Servicios de fotografía",
    "749500 Servicios de envase y empaque",
    "749600 Servicios de impresión heliográfica, fotocopia y otras formas de reproducciones",
    "749900 Servicios empresariales n.c.p.",
    "751100 Servicios generales de la administración pública(Incluye el desempeño de funciones ejecutivas y legislativas de administración por parte de las entidades de la administración central, regional y local; la administración y supervisión de asuntos fiscales;",
    "751200 Servicios para la regulación de las actividades sanitarias, educativas, culturales, y restantes serviciossociales, excepto seguridad social obligatoria(Incluye la gestión administrativa de programas destinados a mejorar el bienestar de los ciudadanos)",
    "751300 Servicios para la regulación de la actividad económica(Incluye la administración pública y la regulaciónde varios sectores económicos; la gestión administrativa de actividades de carácter laboral; la aplicación de políticas de desarrollo regional)",
    "751900 Servicios auxiliares para los servicios generales de la Administración Pública n.c.p.(Incluye las actividades de servicios generales y de personal; la administración, dirección y apoyo de servicios generales, compras y suministros, etc. )",
    "752100 Servicios de asuntos exteriores",
    "752200 Servicios de defensa",
    "752300 Servicios de justicia",
    "752400 Servicios para el orden público y la seguridad",
    "752500 Servicios de protección civil",
    "753000 Servicios de la seguridad social obligatoria",
    "801000 Enseñanza inicial y primaria",
    "802100 Enseñanza secundaria de formación general",
    "802200 Enseñanza secundaria de formación técnica y profesional",
    "803100 Enseñanza terciaria",
    "803200 Enseñanza universitaria excepto formación de posgrado",
    "803300 Formación de posgrado",
    "809000 Enseñanza para adultos y servicios de enseñanza n.c.p.(Incluye instrucción impartida mediante programasde radio, televisión, correspondencia y otros medios de comunicación, escuelas de manejo, actividades de enseñanza a domicilio y/o particulares, etc.)",
    "851110 Servicios de internación",
    "851120 Servicios de hospital de día(Incluye las actividades de tratamiento que no necesitan hospitalizacióna tiempo completo, tales como tratamientos oncológicos; infectológicos; dialíticos; atención de la salud mental; atención pediátrica; atención gerontológic",
    "851190 Servicios hospitalarios n.c.p.",
    "851210 Servicios de atención ambulatoria(Incluye las actividades de consultorios médicos deestablecimientos sin internación, consultorios de guardia para resolver urgencias médicas, vacunatorios, centros del primer nivel de atención, etc. Los servicios de cirug",
    "851220 Servicios de atención domiciliaria programada(Incluye las actividades llevadas a caboen establecimientos que ofrecen atención por módulos a domicilio y actividades de agentes sanitarios relacionados con la prevención y educación para la salud)",
    "851300 Servicios odontológicos",
    "851400 Servicios de diagnóstico(Incluye las actividades de laboratorios de análisis clínicosy patológicos,centros de diagnóstico por imágenes, centros de endoscopía, de electrodiagnóstico, consultorios de hemodinamia, etc.)",
    "851500 Servicios de tratamiento(Incluye las actividades de centros de cobaltoterapia, de radiología convencional, de acelerador lineal de rehabilitación física, de psicoterapia, de hemoterapia, de rehabilitación psíquica, unidades de hemodiálisis, centros de med",
    "851600 Servicios de emergencias y traslados",
    "851900 Servicios relacionados con la salud humana n.c.p.",
    "852000 Servicios veterinarios",
    "853110 Servicios de atención a ancianos con alojamiento",
    "853120 Servicios de atención a personas minusválidas con alojamiento",
    "853130 Servicios de atención a menores con alojamiento",
    "853140 Servicios de atención a mujeres con alojamiento",
    "853190 Servicios sociales con alojamiento n.c.p.",
    "853200 Servicios sociales sin alojamiento",
    "900010 Recolección, reducción y eliminación de desperdicios",
    "900020 Servicios de depuración de aguas residuales, alcantarillado y cloacas",
    "900090 Servicios de saneamiento público n.c.p.",
    "911100 Servicios de federaciones de asociaciones, cámaras, gremios y organizaciones similares",
    "911200 Servicios de asociaciones de especialistas en disciplinas científicas, prácticas profesionales y esferastécnicas",
    "912000 Servicios de sindicatos",
    "919100 Servicios de organizaciones religiosas",
    "919200 Servicios de organizaciones políticas",
    "919900 Servicios de asociaciones n.c.p.",
    "921110 Producción de filmes y videocintas",
    "921120 Distribución de filmes y videocintas",
    "921200 Exhibición de filmes y videocintas",
    "921301 Servicios de radio(No incluye la transmisión, actividad 642010)",
    "921302 Producción y distribución por televisión(No incluye la transmisión, actividad 642010)",
    "921410 Producción de espectáculos teatrales y musicales",
    "921420 Composición y representación de obras teatrales, musicales y artísticas(Incluye a compositores, actores,músicos, conferencistas, pintores, artistas plásticos etc.)",
    "921430 Servicios conexos a la producción de espectáculos teatrales y musicales(Incluye diseñoy manejo de escenografía, montaje de iluminación y sonido, funcionamiento de agencias de venta de billetes de teatro, conciertos, etc.)",
    "921910 Servicios de salones de baile, discotecas y similares",
    "921990 Servicios de espectáculos artísticos y de diversión n.c.p.(Incluye parques de diversión y centros similares, circenses, de títeres, mimos etc.)",
    "922000 Servicios de agencias de noticias y servicios de información(Incluye el suministro dematerial informativo, fotográfico y periodístico a medios de difusión)",
    "923100 Servicios de bibliotecas y archivos",
    "923200 Servicios de museos y preservación de lugares y edificios históricos",
    "923300 Servicios de jardines botánicos, zoológicos y de parques nacionales",
    "924110 Servicios de organización, dirección y gestión de prácticas deportivas y explotación delas instalaciones(Incluye clubes, gimnasios y otras instalaciones para practicar deportes)",
    "924120 Promoción y producción de espectáculos deportivos",
    "924130 Servicios prestados por profesionales y técnicos, para la realización de prácticas deportivas(Incluyelaactividad realizada por deportistas, atletas, entrenadores, instructores, jueces árbitros, escuelas de deporte, etc.)",
    "924910 Servicios de esparcimiento relacionados con juegos de azar y apuestas",
    "924920 Servicios de salones de juegos(Incluye salones de billar, pool, bowling, juegos electrónicos, etc.)",
    "924990 Servicios de entretenimiento n.c.p.",
    "930100 Lavado y limpieza de artículos de tela, cuero y/o de piel, incluso la limpieza en seco",
    "930201 Servicios de peluquería",
    "930202 Servicios de tratamiento de belleza, excepto los de peluquería",
    "930300 Pompas fúnebres y servicios conexos",
    "930910 Servicios para el mantenimiento físico-corporal(Incluye baños turcos, saunas, solarios, centros de masajes y adelgazamiento, etc.)",
    "930990 Servicios n.c.p.(Incluye actividades de astrología y espiritismo, las realizadas con fines sociales comoagencias matrimoniales, de investigaciones genealógicas, de contratación de acompañantes, la actividad de lustrabotas, acomodadores de autos, etc.)",
    "950000 Servicios de hogares privados que contratan servicio doméstico",
    "990000 Servicios de organizaciones y órganos extraterritoriales",
  ],
  };
})();
